filebeat.inputs:
  - type: log
    paths:
      - "/var/log/filebeat/*"
    json.keys_under_root: true
    json.add_error_key: true
    json.overwrite_keys: true

    fields:
      application: tfa-web
      stage: lab
    fields_under_root: true

output.logstash:
  hosts: ["logstash:5044"]