global:
  scrape_interval: 1m

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - rules.yml

scrape_configs:
  - job_name: prometheus
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090

  - job_name: node
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - node-exporter:9100

  - job_name: cadvisor
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - cadvisor:8080

  - job_name: appication
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
      - targets:
          - application:8081
